"""Generate gateway embed sources from data/m5os_session_gateway.bin (CI + local)."""
from __future__ import annotations

import sys
from pathlib import Path

PROJECT_DIR = Path(__file__).resolve().parents[1]
DATA_BIN = PROJECT_DIR / "data" / "m5os_session_gateway.bin"
EMBED_H = PROJECT_DIR / "include" / "m5os_gateway_embed.h"
EMBED_CPP = PROJECT_DIR / "src" / "m5os_gateway_embed.cpp"


def write_embed(data: bytes) -> None:
    if not data or data[0] != 0xE9:
        raise RuntimeError("gateway bin missing ESP image magic 0xE9")
    lines = []
    for i in range(0, len(data), 16):
        chunk = data[i : i + 16]
        lines.append("    " + ", ".join("0x%02x" % b for b in chunk))
    body = ",\n".join(lines)
    EMBED_H.parent.mkdir(parents=True, exist_ok=True)
    EMBED_H.write_text(
        "// Auto-generated by scripts/gen_gateway_embed_from_data.py — do not edit.\n"
        "#pragma once\n"
        "#include <cstddef>\n"
        "#include <cstdint>\n"
        "namespace m5os::gateway_embed {\n"
        "extern const uint8_t kData[];\n"
        "extern const size_t kSize;\n"
        "}  // namespace m5os::gateway_embed\n",
        encoding="utf-8",
    )
    EMBED_CPP.parent.mkdir(parents=True, exist_ok=True)
    EMBED_CPP.write_text(
        "// Auto-generated by scripts/gen_gateway_embed_from_data.py — do not edit.\n"
        '#include "m5os_gateway_embed.h"\n'
        "namespace m5os::gateway_embed {\n"
        "const size_t kSize = %u;\n"
        "alignas(4) const uint8_t kData[kSize] = {\n"
        "%s\n"
        "};\n"
        "}  // namespace m5os::gateway_embed\n" % (len(data), body),
        encoding="utf-8",
    )
    print("M5 OS: embedded session gateway (%u bytes)" % len(data))


def main() -> int:
    if not DATA_BIN.is_file():
        print("missing gateway bin: %s" % DATA_BIN, file=sys.stderr)
        return 1
    write_embed(DATA_BIN.read_bytes())
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
