"""Build session gateway and embed firmware for Load app auto-install."""
Import("env")
import os
import subprocess
import sys
from pathlib import Path

PROJECT_DIR = Path(env.subst("$PROJECT_DIR"))
GATEWAY_ENV = "m5os-session-gateway"
GATEWAY_SRC = PROJECT_DIR / "src" / "session_gateway_main.cpp"
GATEWAY_SHARED = PROJECT_DIR / "include" / "m5os_gateway_shared.h"
PLATFORMIO_INI = PROJECT_DIR / "platformio.ini"
GATEWAY_BUILD_BIN = PROJECT_DIR / ".pio" / "build" / GATEWAY_ENV / "firmware.bin"
DATA_BIN = PROJECT_DIR / "data" / "m5os_session_gateway.bin"
EMBED_H = PROJECT_DIR / "include" / "m5os_gateway_embed.h"
EMBED_CPP = PROJECT_DIR / "src" / "m5os_gateway_embed.cpp"
STAMP = PROJECT_DIR / ".pio" / "gateway_embed.stamp"


def _newest_mtime(paths):
    times = [p.stat().st_mtime for p in paths if p.is_file()]
    return max(times) if times else 0.0


def _needs_rebuild() -> bool:
    if not EMBED_CPP.is_file() or not EMBED_H.is_file() or not DATA_BIN.is_file():
        return True
    if not GATEWAY_BUILD_BIN.is_file():
        return True
    src_mtime = _newest_mtime([GATEWAY_SRC, GATEWAY_SHARED, PLATFORMIO_INI])
    out_mtime = min(EMBED_CPP.stat().st_mtime, DATA_BIN.stat().st_mtime)
    return src_mtime > out_mtime or GATEWAY_BUILD_BIN.stat().st_mtime > out_mtime


def _run_gateway_build(source=None, target=None, env=None):
    active_env = env if env is not None else globals()["env"]
    if os.environ.get("M5OS_SKIP_GATEWAY_EMBED", "").strip().lower() in ("1", "true", "yes"):
        if not EMBED_CPP.is_file():
            raise RuntimeError(
                "M5OS_SKIP_GATEWAY_EMBED set but %s is missing — run build_session_gateway.ps1"
                % EMBED_CPP
            )
        print("M5 OS: skip gateway embed build (M5OS_SKIP_GATEWAY_EMBED)")
        return
    if active_env.subst("$PIOENV") == GATEWAY_ENV:
        return
    if not _needs_rebuild():
        print("M5 OS: using embedded session gateway (%s)" % DATA_BIN)
        return
    cmd = [sys.executable, "-m", "platformio", "run", "-e", GATEWAY_ENV]
    print("M5 OS: building session gateway (%s)" % GATEWAY_ENV)
    subprocess.check_call(cmd, cwd=str(PROJECT_DIR))
    if not GATEWAY_BUILD_BIN.is_file():
        raise RuntimeError("gateway build missing: %s" % GATEWAY_BUILD_BIN)
    _write_embed(GATEWAY_BUILD_BIN.read_bytes())


def _write_embed(data: bytes):
    if not data or data[0] != 0xE9:
        raise RuntimeError("gateway firmware.bin missing ESP magic 0xE9")
    DATA_BIN.parent.mkdir(parents=True, exist_ok=True)
    DATA_BIN.write_bytes(data)
    lines = []
    for i in range(0, len(data), 16):
        chunk = data[i : i + 16]
        lines.append("    " + ", ".join("0x%02x" % b for b in chunk))
    body = ",\n".join(lines)
    EMBED_H.write_text(
        "// Auto-generated by scripts/prebuild_gateway_embed.py — do not edit.\n"
        "#pragma once\n"
        "#include <cstddef>\n"
        "#include <cstdint>\n"
        "namespace m5os::gateway_embed {\n"
        "extern const uint8_t kData[];\n"
        "extern const size_t kSize;\n"
        "}  // namespace m5os::gateway_embed\n",
        encoding="utf-8",
    )
    EMBED_CPP.write_text(
        "// Auto-generated by scripts/prebuild_gateway_embed.py — do not edit.\n"
        '#include "m5os_gateway_embed.h"\n'
        "namespace m5os::gateway_embed {\n"
        "const size_t kSize = %u;\n"
        "alignas(4) const uint8_t kData[kSize] = {\n"
        "%s\n"
        "};\n"
        "}  // namespace m5os::gateway_embed\n" % (len(data), body),
        encoding="utf-8",
    )
    STAMP.write_text(str(len(data)), encoding="utf-8")
    print("M5 OS: embedded session gateway (%u bytes) -> %s" % (len(data), EMBED_CPP))


# Generate before any .cpp compiles (buildprog pre-action is too late for headers).
_run_gateway_build()
env.AddPreAction("buildprog", _run_gateway_build)
